/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack;

import javax.swing.JLabel;

/**
 *
 * @author Arin
 */
public class CharBlock extends JLabel {
    
    private CharBlockTwin twin = new CharBlockTwin();
    
    /**
     * Creates new form CharBlock
     */
    public CharBlock() {
        initComponents();
    }
    
     public String getBlockType()
    {
        return twin.getBlockType();
    }
    
    public String getBlockName()
    {
        return twin.getBlockName();
    }
    
    public void setValue(char val)
    {
        String valueString = val + "";
        twin.setValueString(valueString);
    }
    
    public char getValue()
    {
        char value = twin.getValueString().charAt(0);
        return value;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/char.png"))); // NOI18N
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
