/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack;

import javax.swing.JLabel;

/**
 *
 * @author Arin
 */
public class StringBlock extends JLabel {

    private final StringBlockTwin twin = new StringBlockTwin();
    
    /**
     * Creates new form stringBlock
     */
    public StringBlock() {
        initComponents();
    }
    
    public String getBlockType()
    {
        return twin.getBlockType();
    }
    
    public String getBlockName()
    {
        return twin.getBlockName();
    }
    
    public void setValue(String val)
    {
        twin.setValueString(val);
    }
    
    public String getValue()
    {
        return twin.getValueString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/string.png"))); // NOI18N
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
